name: CI

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Setup repo
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: '*'
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Audit dependencies
        run: npm audit --audit-level=high
        
      - name: Run expo doctor
        run: npx expo-doctor

      - name: Run linter
        run: npm run lint

      - name: Run tests
        run: npm test

